In [1]:
import numpy as np

# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [10]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(50, size=(5, 5))
print("Original array: ")
print(array, "\n")

# Replace all the elements in the third column with 1
array[:, 2] = 1
print("Modified array: ")
print(array)

Original array: 
[[20 31 48 33  4]
 [46  1 13  3  1]
 [27  9  3 10 47]
 [46  5 34 28 20]
 [ 6  1  7 45  7]] 

Modified array: 
[[20 31  1 33  4]
 [46  1  1  3  1]
 [27  9  1 10 47]
 [46  5  1 28 20]
 [ 6  1  1 45  7]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [17]:
array2 = np.random.randint(1, 16, size=(4, 4))
print("Original array: ")
print(array2)

# Replace the diagonal elements with 0
np.fill_diagonal(array2, 0)
print("Modified array: ")
print(array2)

Original array: 
[[14  2 13 15]
 [10 15  6  2]
 [ 3  3 10  2]
 [ 2  6  1 12]]
Modified array: 
[[ 0  2 13 15]
 [10  0  6  2]
 [ 3  3  0  2]
 [ 2  6  1  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [21]:
# creating the array
array = np.random.randint(1, 3, size=(6, 6))
print("Original array:")
print(array)

# Extracting the sub-array of 3rd to 5th row, 2nd to 4th cols
sub_array = array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

Original array:
[[1 1 2 2 2 2]
 [2 1 2 2 1 2]
 [1 1 1 1 2 1]
 [2 2 2 2 1 2]
 [1 2 2 1 1 1]
 [1 2 1 2 1 1]]
Sub-array:
[[1 1 1]
 [2 2 2]
 [2 2 1]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [25]:
# creating the array
array = np.random.randint(1, 21, size=(6, 6))
print("Original array:")
print(array)

# extracting element
border_elements = np.concatenate((array[0 , :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements: ")
print(border_elements)

Original array:
[[ 9  7 16  7  2  9]
 [ 2 14 18 18  1  8]
 [14  5 11  1  6 14]
 [ 5 13  8 10 20 12]
 [16  9 19 15 11  6]
 [10 20 20 17 11 16]]
Border elements: 
[ 9  7 16  7  2  9 10 20 20 17 11 16  2 14  5 16  8 14 12  6]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [28]:
arr1 = np.random.randint(1, 21, size=(3, 4))
arr2 = np.random.randint(1, 10, size=(3, 4))

addition = arr1 + arr2
subtraction = arr1 - arr2
multi = arr1 * arr2
div = arr1 / arr2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multi)
print("Element-wise division:")
print(div)

Element-wise addition:
[[ 9 18 15 27]
 [11  2 15  8]
 [16 23 11 12]]
Element-wise subtraction:
[[ 3 14 -3 11]
 [ 1  0  3  0]
 [ 4 11 -1  6]]
Element-wise multiplication:
[[ 18  32  54 152]
 [ 30   1  54  16]
 [ 60 102  30  27]]
Element-wise division:
[[2.         8.         0.66666667 2.375     ]
 [1.2        1.         1.5        1.        ]
 [1.66666667 2.83333333 0.83333333 3.        ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [30]:
arr1 = np.random.randint(1, 17, size=(4, 4))

# Compute the row-wise and col-wise sum
row_sum = np.sum(arr1, axis=1)
col_sum = np.sum(arr1, axis = 0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(col_sum)

Row-wise sum:
[26 36 44 43]
Column-wise sum:
[34 33 39 43]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [35]:
array = np.random.randint(1, 21, size=(5, 5))

mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)
print("Mean: ", mean)
print("Median: ", median)
print("Standard Deviation: ", std_dev)
print("Variance: ", variance)

Mean:  10.04
Median:  10.0
Standard Deviation:  5.517100687861333
Variance:  30.438399999999998


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [40]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape(3, 3)
print("Original array:")
print(array)

# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array: ")
print(normalized_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array: 
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [43]:
array1 = np.random.randint(1, 21, size=(3, 3))
row_array = np.random.randint(1, 21, size=(3,))

print("Original array:")
print(array1)
print("1D array:")
print(row_array)

new_array = array1 + row_array
print("New Array:")
print(new_array)

Original array:
[[15 15 12]
 [14 17 17]
 [15 13  6]]
1D array:
[13  3 15]
New Array:
[[28 18 27]
 [27 20 32]
 [28 16 21]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [49]:
array = np.random.randint(1, 11, size=(4, 4))
row_array = np.random.randint(1, 11, size=(4, ))

print("Original array:")
print(array)
print("1D array:")
print(row_array)

new_array = array - row_array[:, np.newaxis]
print("New Array:")
print(new_array)

Original array:
[[ 8  3  8  4]
 [ 5  2  1  9]
 [ 4  5  3 10]
 [ 5  2  4  8]]
1D array:
[2 9 9 8]
New Array:
[[ 6  1  6  2]
 [-4 -7 -8  0]
 [-5 -4 -6  1]
 [-3 -6 -4  0]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [ ]:
matrix = np.random.randint(1, 10, size=(3, 3))
# printing the matrix
print("Matrix: ")
print(matrix)

determinant = np.linalg.det(matrix)
print("Determinant: ", determinant)

inverse = np.linalg.inv(matrix)
print("Inverse: ")
print(inverse)

eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues: ")
print(eigenvalues)

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [8]:
array = np.random.randint(1, 10, size=(3, 3))
print(array)

#Reshape to shape (1, 9)
reshaped_array1 = array.reshape(1, 9)
print(reshaped_array1)

#Reshape to shape (9, 1)
reshaped_array2 = array.reshape(9, 1)
print(reshaped_array2)

[[7 6 8]
 [9 3 4]
 [2 9 9]]
[[7 6 8 9 3 4 2 9 9]]
[[7]
 [6]
 [8]
 [9]
 [3]
 [4]
 [2]
 [9]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [9]:
array = np.random.randint(1, 21, size=(5, 5))

print("Original Array: ")
print(array)

array = array.flatten()
print("Flattened array: ")
print(array)

array = array.reshape(5, 5)
print("Reshaped array: ")
print(array)


Original Array: 
[[ 2  8 10 12 15]
 [ 4 15  1  2  4]
 [12  4  6  2 11]
 [11  4 16 19  2]
 [15  3 13  8  9]]
Flattened array: 
[ 2  8 10 12 15  4 15  1  2  4 12  4  6  2 11 11  4 16 19  2 15  3 13  8
  9]
Reshaped array: 
[[ 2  8 10 12 15]
 [ 4 15  1  2  4]
 [12  4  6  2 11]
 [11  4 16 19  2]
 [15  3 13  8  9]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [20]:
array = np.random.randint(1, 21, size=(5, 5))

print("Original array:")
print(array)

listt = array[[0, 0, -1, -1], [0, -1, 0, -1]]

print("\nCorner elements:")
print(listt)

Original array:
[[10 19  7 19 16]
 [ 5 10  9 18  4]
 [12 17 10 20 19]
 [13 15 13  4  1]
 [16  7 11 14  4]]

Corner elements:
[10 16 16  4]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [21]:
array = np.random.randint(1, 21, size=(4, 4))

print("Original array:")
print(array)

array[array > 10] = 10
print("Modified array: ")
print(array)

Original array:
[[ 9 12 15  7]
 [11  6  5 15]
 [17 13 14  6]
 [ 7  5 17 12]]
Modified array: 
[[ 9 10 10  7]
 [10  6  5 10]
 [10 10 10  6]
 [ 7  5 10 10]]
