In [1]:
import numpy as np

# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [10]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(50, size=(5, 5))
print("Original array: ")
print(array, "\n")

# Replace all the elements in the third column with 1
array[:, 2] = 1
print("Modified array: ")
print(array)

Original array: 
[[20 31 48 33  4]
 [46  1 13  3  1]
 [27  9  3 10 47]
 [46  5 34 28 20]
 [ 6  1  7 45  7]] 

Modified array: 
[[20 31  1 33  4]
 [46  1  1  3  1]
 [27  9  1 10 47]
 [46  5  1 28 20]
 [ 6  1  1 45  7]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [17]:
array2 = np.random.randint(1, 16, size=(4, 4))
print("Original array: ")
print(array2)

# Replace the diagonal elements with 0
np.fill_diagonal(array2, 0)
print("Modified array: ")
print(array2)

Original array: 
[[14  2 13 15]
 [10 15  6  2]
 [ 3  3 10  2]
 [ 2  6  1 12]]
Modified array: 
[[ 0  2 13 15]
 [10  0  6  2]
 [ 3  3  0  2]
 [ 2  6  1  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [21]:
# creating the array
array = np.random.randint(1, 3, size=(6, 6))
print("Original array:")
print(array)

# Extracting the sub-array of 3rd to 5th row, 2nd to 4th cols
sub_array = array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

Original array:
[[1 1 2 2 2 2]
 [2 1 2 2 1 2]
 [1 1 1 1 2 1]
 [2 2 2 2 1 2]
 [1 2 2 1 1 1]
 [1 2 1 2 1 1]]
Sub-array:
[[1 1 1]
 [2 2 2]
 [2 2 1]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [25]:
# creating the array
array = np.random.randint(1, 21, size=(6, 6))
print("Original array:")
print(array)

# extracting element
border_elements = np.concatenate((array[0 , :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements: ")
print(border_elements)

Original array:
[[ 9  7 16  7  2  9]
 [ 2 14 18 18  1  8]
 [14  5 11  1  6 14]
 [ 5 13  8 10 20 12]
 [16  9 19 15 11  6]
 [10 20 20 17 11 16]]
Border elements: 
[ 9  7 16  7  2  9 10 20 20 17 11 16  2 14  5 16  8 14 12  6]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [28]:
arr1 = np.random.randint(1, 21, size=(3, 4))
arr2 = np.random.randint(1, 10, size=(3, 4))

addition = arr1 + arr2
subtraction = arr1 - arr2
multi = arr1 * arr2
div = arr1 / arr2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multi)
print("Element-wise division:")
print(div)

Element-wise addition:
[[ 9 18 15 27]
 [11  2 15  8]
 [16 23 11 12]]
Element-wise subtraction:
[[ 3 14 -3 11]
 [ 1  0  3  0]
 [ 4 11 -1  6]]
Element-wise multiplication:
[[ 18  32  54 152]
 [ 30   1  54  16]
 [ 60 102  30  27]]
Element-wise division:
[[2.         8.         0.66666667 2.375     ]
 [1.2        1.         1.5        1.        ]
 [1.66666667 2.83333333 0.83333333 3.        ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [30]:
arr1 = np.random.randint(1, 17, size=(4, 4))

# Compute the row-wise and col-wise sum
row_sum = np.sum(arr1, axis=1)
col_sum = np.sum(arr1, axis = 0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(col_sum)

Row-wise sum:
[26 36 44 43]
Column-wise sum:
[34 33 39 43]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [35]:
array = np.random.randint(1, 21, size=(5, 5))

mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)
print("Mean: ", mean)
print("Median: ", median)
print("Standard Deviation: ", std_dev)
print("Variance: ", variance)

Mean:  10.04
Median:  10.0
Standard Deviation:  5.517100687861333
Variance:  30.438399999999998


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [40]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape(3, 3)
print("Original array:")
print(array)

# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array: ")
print(normalized_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array: 
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
