# Numpy
Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy.

In [7]:
# To install numpy on your local machine
%pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [8]:
# Import numpy to use
import numpy as np      # np is an alias of numpy

## Create Array Using Numpy

#### Create an 1D Array

In [9]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])           # inside the parenthesis, i can give lists, tuples etc
print(arr1)                                # printing an array
print(type(arr1))
print(arr1.shape)                          # print the dimension

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


#### Create a 2D Array

In [10]:
# reshaping 1d to a 2d array
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape((1, 5))        # 1 row, and 5 columns

array([[1, 2, 3, 4, 5]])

In [11]:
arr2 = np.array([[1, 2, 3, 4, 5]])
arr2.shape

(1, 5)

In [12]:
# Creating 2D array, but columns need to be the same size
arr2 = np.array([[1, 2, 3, 4, 5],[4, 5, 6, 7, 8]])
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [4 5 6 7 8]]


(2, 5)

## Quick Recap

In [13]:
# Attributes of NumPy
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: ", arr)
print("Shape: ", arr.shape)         # Output: (2, 3)
print("Number of dimensions: ", arr.ndim)   # Output: 2
print("Size (number of elements): ", arr.size)  # Output: 6
print("Data type: ", arr.dtype)     # Output: int64 (may vary based on platforms)
print("Item size (in bytes): ", arr.itemsize)   # Output: 8 (may vary based on platforms)

Array:  [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Data type:  int64
Item size (in bytes):  8


### Matrix Operations

In [14]:
# it starts from 0 and goes till 10, with 2 being how much it should skip
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

### Ones, and Zeros

In [16]:
## Create an array, but every value is 0
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
# Create 2D array, but every value will be 1
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Identity Matrix
All the diagonal values will be 1, other elements will be 0

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])