## Numpy Vectorized Operation

In [4]:
import numpy as np

array1 = np.array([1, 2, 3 ,4 ,5])
array2 = np.array([10, 20, 30, 40, 50])

### Element wise addition
print("Addition: ", array1 + array2)

### Element wise subtraction
print("Subtraction: ", array1 - array2)

### Element wise multiplication
print("Multiplication: ", array1 * array2)

### Element wise division
print("Division: ", array1 / array2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


### Universal functions

In [6]:
arr = np.array([2, 3, 4, 5, 6])

## square root
print(np.sqrt(arr))

## exponential
print(np.exp(arr))

## sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


### Array Slicing and Indexing

In [7]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr[0])      # 1st row, Output: [1, 2, 3, 4]
print(arr[0][0])   # 1st element of 1st row, Output: 1

[1 2 3 4]
1


In [ ]:
arr[1:]     # second row to last row

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
arr[1:, 2:]     # second row to last row, but from second column to last col

array([[ 7,  8],
       [11, 12]])

In [ ]:
arr[0:2, 2:]    # from first row to second row, but second col to col

array([[3, 4],
       [7, 8]])

In [18]:
"""To pick 6, 7, 10, 11
Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
"""
arr[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

### Modify Array Elements

In [20]:
arr[0, 0] = 100

print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [21]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]
